version: '3.8'

services:
  php-fpm:
    build:
      context: .
    working_dir: /var/www/html
    expose:
      - 9001  # Use a different port, for example, 9001
    command: ["php-fpm"]

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html:ro
    depends_on:
      - php-fpm
