version: '3'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php

