name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker-compose up -d
        docker-compose exec php composer install
        docker-compose exec php vendor/bin/phpunit
      env:
        DB_HOST: mysql
        DB_USER: root
        DB_PASS: root
